AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  deploysam

  Sample SAM Template for deploysam

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60

Resources:
  ListS3BucketsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: ListS3Buckets
      Description: SAM demo for listing s3 buckets
      Role: !ImportValue SAMIamRole
      CodeUri: lists3buckets/
      Handler: main.lambda_handler
      Runtime: python3.7
      Events:
        ListS3BucketsAPI:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /lists3buckets
            Method: get
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ListS3BucketsAPI:
    Description: "API Gateway endpoint URL for Prod stage for ListS3Buckets function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/lists3buckets/"
  ListS3BucketsFunction:
    Description: "ListS3Buckets Lambda Function ARN"
    Value: !GetAtt ListS3BucketsFunction.Arn
  # ListS3BucketsFunctionIamRole:
  #   Description: "Implicit IAM Role created for ListS3Buckets function"
  #   Value: !GetAtt SAMRole.Arn
